apiVersion: apps/v1
kind: Deployment
metadata:
  name: checklist-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checklist-be
  template:
    metadata:
      labels:
        app: checklist-be
    spec:
      containers:
        - name: be
          image: acrworkflow1713887802434.azurecr.io/image-workflow-1713887802434